### ISSUE TITLE
bootstrap-combined 2.1.1 doesn't contain bootstrap-responsive

### ISSUE THREAD

**Issue by beaumartinez** [jsdelivr/bootstrapcdn#41]
Bootstrap combined 2.1.1 is the same as "regular" Bootstrap—it doesn't have any of Bootstrap responsive's CSS. Have a look—

http://netdna.bootstrapcdn.com/twitter-bootstrap/2.1.1/css/bootstrap-combined.min.css
http://netdna.bootstrapcdn.com/twitter-bootstrap/2.1.1/css/bootstrap.min.css

Cheers

**Comment by yeskayldn** [comment]
I am using bootstrap 3.2.0 and can't find the combined.min.css

The code(http://tarruda.github.io/bootstrap-datetimepicker/) works with 2.2.2 fails to work with 3.2.0.

Error is "Uncaught TypeError: undefined is not a function "

Any suggessions please.

Thanks in advance.

**Comment by jdorfman** [comment]
@yeskayldn we combine everything now by default
